[package]
name = "ebpf_program"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { workspace = true }

[[bin]]
name = "ebpf_program"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
